# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

  jobs:
    post_checkout:
      - git reset --hard
      - git clean -fdx
    post_create_environment:
      - pip install poetry==1.3.1
      - poetry config virtualenvs.create false
    post_install:
      - "echo 'def build(setup_kwargs): pass' > build.py"
      - poetry install --with docs
      - find .

sphinx:
  configuration: docs/conf.py
