name: Push
on: [push]

jobs:
  checks:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.3.1"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install --with dev
      - name: Run tests with coverage
        run: poetry run coverage run -m unittest
      - name: Show coverage report
        run: poetry run coverage report -m
      - name: Run black
        run: poetry run black . --check
      - name: Run isort
        run: poetry run isort . --check-only --profile black
      - name: Run docformatter
        run: poetry run docformatter . --recursive --check
#       - name: Run flake8
#         run: poetry run flake8 .
#       - name: Run bandit
#         run: poetry run bandit .
#       - name: Run saftey
#         run: poetry run safety check
