name: Release
on:
  release:
    types:
      - created

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.13"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential
          pip install conan
      - uses: wntrblm/nox@main
      - name: Build and Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          nox -s build-cpp
          pip install poetry
          poetry build
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish
